markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: true
redcarpet:  
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "underline", "highlight", "with_toc_data", "quote"]
exclude: ['README.md']
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
title: Open Hardware Laboratory Lampa
